users/chunyang: svn-open: Fix indent in previous commit (https://trac.macports.org/changeset/137532)
git-svn-id: https://svn.macports.org/repository/macports/users/chunyang@137533 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/svn-open/svn-open b/svn-open/svn-open
--- a/svn-open/svn-open
+++ b/svn-open/svn-open
@@ -16,8 +16,8 @@ function usage {
 }
 
 function error_exit {
-        echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
-        exit 1
+    echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+    exit 1
 }
 
 svn info &> /dev/null || error_exit "$(pwd) not registered"
